services:
  db:
    image: postgres:16
    container_name: alerta_cidadao_db_prod
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - pgdata_prod:/var/lib/postgresql/data
    restart: always
    networks:
      - app_network
  
  api:
    image: rafadev1/alerta-cidadao-api:latest
    container_name: alerta_cidadao_api_prod
    depends_on:
      - db
    environment:
      DATABASE_URL: "postgresql://${DB_USER}:${DB_PASS}@db:5432/${DB_NAME}"
      PORT: 3000
    ports:
      - "80:3000"
    restart: always
    networks:
      - app_network

volumes:
  pgdata_prod:

networks:
  app_network: